---
- name: Playbook to Fully Setup and Configure a new User with a Role
  hosts: serverc
  vars:
    ansible_user_name: travis
    ansible_user_password: redhat
    ssh_key_answer: no
  collections:
    - ansible.posix  ### Need to cheat here
  roles:
    - tmichett.ansiblize
