---
- name: Playbook to Create User and Sudoers without Password
  hosts: serverb
  tasks:
    - name: Create User Named Travis
      user:
        name: travis 
        uid: 1040 
        comment: "Travis Michette" 
        group: wheel

    - name: Create User in Sudoers File
      copy:
        content: "travis ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/travis
        validate: /usr/sbin/visudo -csf %s