---
- name: Playbook to Cleanup MOTD for Testing Custom EE
  hosts: serverb
  become: true
  tasks:

    - name: Reset MOTD
      copy:
        content: "I'm the clean MOTD Banner\n"
        dest: /etc/motd.d/banner
